import dotenv from "dotenv";

dotenv.config();

const { PORT, JWT_SECRET, DATABASE_URI , REFRESH_TOKEN_SECRET, ACCESS_TOKEN_SECRET, CLOUDINARY_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET} = process.env;

export const _config = {
  PORT,
  JWT_SECRET,
  DATABASE_URI,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET
};
  