import dotenv from "dotenv";

dotenv.config();

const {
  PORT,
  JWT_SECRET,
  DATABASE_URI,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ARCJET_KEY,
  AWS_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME,
} = process.env;

export const _config = {
  ARCJET_KEY,
  PORT,
  JWT_SECRET,
  DATABASE_URI,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  AWS_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME,
};
